version: '3.8'

name: kafka-chat

services:

  auth-service:
    &auth-service
    container_name: auth-service
    hostname: auth
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    build: 
      context: ./services/auth/
      dockerfile: ./Dockerfile
    env_file:
      - ./services/auth/.env.production
    networks:
      - internal
    ports:
      - 8000:8000
    volumes:
      - ./services/auth/src:/app/src
    command: sh -c "alembic upgrade head && uvicorn src.presentation.main:create_app --host 0.0.0.0 --port 8000 --reload"

  user-service:
    container_name: user-service
    hostname: users
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: ./services/users/
      dockerfile: ./Dockerfile
    env_file:
      - ./services/users/.env.production
    networks:
      - internal
    ports:
      - 8001:8000
    volumes:
      - ./services/users/src:/app/src
    command: sh -c "uvicorn src.main:create_app --host 0.0.0.0 --port 8000 --reload"

  notifications-service:
    container_name: notifications-service
    hostname: notifications
    depends_on:
      kafka:
        condition: service_healthy
    build: 
      context: ./services/notifications/
      dockerfile: ./Dockerfile
    env_file:
      - ./services/notifications/.env.production
    networks:
      - internal
    volumes:
      - ./services/notifications/app/:/app/
    command: sh -c "python ./main.py"

  nginx:
    container_name: nginx
    hostname: nginx
    build: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    networks:
      - internal

  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    hostname: postgres
    env_file:
      - ./services/auth/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 22181:2181
    networks:
    - internal

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    healthcheck: 
      test: nc -z localhost 29092
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    networks:
      - internal


  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - internal
    
volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
